---
title: "reproducible_workflow"
author: "Krish_(B2)"
format: html
editor: visual
---

## Filtlong setup

Step 1: create environment

```{bash}
#| eval: false
conda create --name partner_Krish(B1)_filtlong -y
```

Step 2: activate environment

```{bash}
#| eval: false
conda activate partner_Krish(B1)_filtlong
```

Step 3: install filtlong

```{bash}
#| eval: false
onda install -c bioconda filtlong
```

## Docker setup and Dorado info

Dorado is a high-performance, open-source command-line basecaller developed by **Oxford Nanopore Technologies** (ONT) to convert raw electrical signals (POD5/Fast5) into DNA/RNA sequences.

```{bash}
#| eval: false
#open the docker app on the desktop
#open the terminal
docker pull --platform linux/amd64 nanoporetech/dorado:latest
docker run --rm --platform linux/amd64 -it nanoporetech/dorado:latest --help
```

## Tidyverse setup

```{r}
#| eco: "false"
library("tidyverse")
```

```{r}
yeast_mata_data <- read.csv("yeast_genome_metadata.csv")
yeast_mata_data_filtered <- yeast_mata_data%>%
  filter(gc_content < 40)%>% 
  mutate(quality_status = if_else(sequencing_depth > 50, "High", "Low"))

high_quality_samples <- yeast_mata_data_filtered%>%
  filter(quality_status == "High") %>% select(sample_id)

high_quality_samples_vector <- high_quality_samples$sample_id
write_csv(yeast_mata_data_filtered, "partner_Krish(B2)_filtered.csv")

```

```{r}
ggplot(data = yeast_mata_data_filtered, aes(x = sequencing_depth)) +
  geom_histogram() +
  labs(title = "Yeast_meta_data", x = "sequencing_depth") +
  theme_minimal()
```
